version: '3.8'

services:
  mariadb:
    image: mariadb:10.8
    restart: always
    ports:
      - 3307:3306
    volumes:
      - ./mariadb:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_PASSWORD=admin
      - MYSQL_USER=admin
      - MYSQL_DATABASE=test
      - MYSQL_TCP_PORT=3306
  phpMyAdmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_PORT:3307
      - PMA_ARBITRARY=1